from .coarsening_base import Coarsen
from .vng import VNG
from .clustering import Cluster
from .clusteringagg import ClusterAgg
from .averaging import Average
from .variation_neighborhoods import VariationNeighborhoods
from .variation_edges import VariationEdges
from .variation_cliques import VariationCliques
from .heavy_edge import HeavyEdge
from .algebraic_jc import AlgebraicJc
from .affinity_gs import AffinityGs
from .kron import Kron